### ISSUE TITLE
Support for TC-39's async iteration proposal?

### ISSUE THREAD

**Issue by jacoscaz** [RubenVerborgh/AsyncIterator#10]
Would it be possible to extend `asynciterator` to support [TC-39's async iteration proposal](https://github.com/tc39/proposal-async-iteration)? It is starting to be implemented by browsers and has landed as a new way to consume streams in Node.js 10.x .

**Comment by RubenVerborgh** [comment]
I might add interface support, but (and this is a bit but) async iteration is a lot slower than asynciterator. It has been a deliberate choice to develop asynciterator, even though the asyc iteration effort was going on, for performance reasons.

So while you could then `for await` over an AsyncIterator, it would not be the preferred way in performance-critical applications.

My colleague @joachimvh did some testing earlier this year: https://github.com/RubenVerborgh/HDT-Node/issues/9#issuecomment-355907431

**Comment by jacoscaz** [comment]
@RubenVerborgh I see! Thank you for pointing me to that.

**Comment by slikts** [comment]
The linked comment seems to talk about testing the transpiled versions of async generators, though; the native performance should be better.

**Comment by RubenVerborgh** [comment]
@joachimvh Do we have native performance tests?

**Comment by joachimvh** [comment]
I just removed the transpilation step now and it did improve but is still much slower than AsyncIterator (usual disclaimer of this not being the most extensive tests ever etc.)

**Comment by LaurensRietveld** [comment]
Perphaps relevant for this discussion: node 10 has (experimental) support for using a readable stream as an async iterator. This would not solve any possible performance issue, but it could mean we wouldnt have to implement an async iterator interface _and_ a streaming interface.
