### ISSUE TITLE
Lazy transform and union iterator never start

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/AsyncIterator#24]
In https://github.com/comunica/comunica/pull/733, I discovered that some other queries started freezing (that didn't freeze before) since asynciterator version 3.0.2.

Related to #22.

Minimal reproducible example:
```
  const arrayIt = new ArrayIterator([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], { autoStart: false });
  const transformit = new TransformIterator(arrayIt, { autoStart: false });
  const unionIt = new UnionIterator([transformit], { autoStart: false });

  // The listeners below are never called
  unionIt.on('data', () => console.log('DATA'));
  unionIt.on('end', () => console.log('ENDED'));
```

It looks like the transform buffer is being filled partially, but its elements are never propagated upwards for some reason.

**Comment by RubenVerborgh** [comment]
Thanks for reporting, fixed in v3.0.3
<img src="https://cdn.dribbble.com/users/172091/screenshots/2949448/tb303_roland.jpg" width=100>
