### ISSUE TITLE
Current task scheduler does not guarantee order

### ISSUE THREAD

**Issue by RubenVerborgh** [RubenVerborgh/AsyncIterator#28]
The snippet at https://github.com/RubenVerborgh/AsyncIterator/blob/668697c568484881f663b786e0b6a037c2cd5ab3/taskscheduler.ts#L13-L21 can result in out-of-order execution when a microtask is scheduled before `setTimeout` has occurred.

**Comment by RubenVerborgh** [comment]
@rubensworks Could you test if https://github.com/RubenVerborgh/AsyncIterator/tree/fix/task-order does not break anything? This should be the final guard before #29 can be released. (It's weird that we have not run into out-of-order bugs yet.)

**Comment by rubensworks** [comment]
Everything seems to work fine! (aside for #30 that is)

**Comment by RubenVerborgh** [comment]
Thank you!
