### ISSUE TITLE
Optimize ArrayIterator

### ISSUE THREAD

**Issue by jeswr** [RubenVerborgh/AsyncIterator#38]
It currently uses `.shift` which is a O(n) operation. So it costs O(n^2) to iterator over.

**Comment by jeswr** [comment]
The BufferedIterator will also suffer similar performance issues when the maxBufferSize, as does the `MultiTransformer` with a large transformerQueue.

**Comment by RubenVerborgh** [comment]
All major JavaScript engines implement behavior that is closer to O(1), see:
- https://lannonbr.com/blog/2020-01-27-shift-optimizations
- https://bugzilla.mozilla.org/show_bug.cgi?id=1348772
- https://github.com/frida/v8/blob/main/src/builtins/array-shift.tq

Trying to be faster ourselves will most likely have the opposite effect.

**Comment by RubenVerborgh** [comment]
Given the discussion in #44, we might want to see if alternatively implementations (notably a linked list) would speed this up.

**Comment by jacoscaz** [comment]
@RubenVerborgh interesting you should say that... I thought exactly the same, and came up with https://github.com/jacoscaz/AsyncIterator/blob/42311b68988a971fc072c896100d7082b4162470/asynciterator.ts#L744-L783 . I'm still testing it. Interested in a PR?

**Comment by RubenVerborgh** [comment]
That's quite perfect and exactly what I had in mind!
Curious about perf; PR welcome!

(Nit: perhaps we should have that code in a separate file and include it.)
