### ISSUE TITLE
use native `queueMicrotask`

### ISSUE THREAD

**Issue by jeswr** [RubenVerborgh/AsyncIterator#39]
Since there is a native [`queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide) function it may be worth considering using it rather than calling `.then` on a resolved promise.

**Comment by jeswr** [comment]
While there have been tricks available that made it possible to enqueue microtasks in the past (such as by creating a promise that resolves immediately), the addition of the [queueMicrotask()](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask) method adds a standard way to introduce a microtask safely and without tricks.

By introducing queueMicrotask(), the quirks that arise when sneaking in using promises to create microtasks can be avoided. For instance, when using promises to create microtasks, exceptions thrown by the callback are reported as rejected promises rather than being reported as standard exceptions. Also, creating and destroying promises takes additional overhead both in terms of time and memory that a function which properly enqueues microtasks avoids.

Source - https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide

**Comment by RubenVerborgh** [comment]
> Since there is a native [`queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide) function it may be worth considering using it rather than calling `.then` on a resolved promise.

But that's what we're doing? https://github.com/RubenVerborgh/AsyncIterator/blob/98565fd19b894a8941480740674301cd85ec2309/taskscheduler.ts#L5-L7

**Comment by jeswr** [comment]
Oh yep - brainslip, nevermind!
