### ISSUE TITLE
WrappingIterator does not destroy sources

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/AsyncIterator#83]
Unlike other iterators, the new WrappingIterator does not destroy sources on end, nor has it a `destroySource` option.

This will likely result in problems where iterators keep running internally for a while (or infinitely), even though they can be stopped.

**Comment by jacoscaz** [comment]
Good point. Is anyone already working on this? I can have a look if not.

**Comment by rubensworks** [comment]
I'm not working on it, so feel free to have a go at it @jacoscaz :-)

For this, it would be good to also keep #84 in mind.
