### ISSUE TITLE
Discussion: Destroy propagation in callback-based TransformIterator

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/AsyncIterator#86]
I don't think it's really a bug, but nevertheless, I think it deserves some discussion.

Yesterday, I discover some edge-cases in which chained iterators would keep on running (due to an infinite iterator in the chain), even though the head of the chain was destroyed.
While destroy calls should be propagated (unless `destroySource` is set to `false`), this was not happening in this case.

The root cause of these problems seemed to be caused by TransformIterators with an (async) callback-based reference to another iterator, where this iterator was created externally.

They shared the following form:
```js
const baseIterator = ...; // Some iterator that has to be created beforehand, and can not be placed in the async callback below.

const transformIt = new TransformIterator(async() => baseIterator.map(...), { autoStart: false });
```

In cases where `transformIt` (or some other iterator in the chain from `transformIt`) was destroyed **before it was being read**, `baseIterator` would not be destroyed.
This makes sense of course, because the callback in the `TransformIterator` is never invoked, which breaks the destroy call chain `baseIterator`.

I've created [a workaround](https://github.com/comunica/comunica/commit/715b8acc122d28d09cbe28c02a1c7b8a7b82d024#diff-a8fdf612bb43b4fd972a47e1661e108b187feae2a73934f74c293b906f54b55c) for these cases, so the problem is solved on my end.
But I thought it would be good to raise this issue here as well. Perhaps it can help someone with debugging in the future.

**Comment by RubenVerborgh** [comment]
Thanks for reporting; however, I don't fully understand the case yet. What is the relationship between `baseIterator` and `transformIt`?

**Comment by rubensworks** [comment]
Ah, apologies, there was a typo in the example. Updated now, should make more sense :-)

**Comment by RubenVerborgh** [comment]
It's a matter of ownership indeed; the `baseIterator` was created outside of the `TransformIterator`, and ownership was never transfered.

Perhaps a `destroyed` event is what we need then?

**Comment by rubensworks** [comment]
> Perhaps a destroyed event is what we need then?

Yes, I think that would help for these cases.

**Comment by RubenVerborgh** [comment]
Super, following up in https://github.com/RubenVerborgh/AsyncIterator/issues/95
