### ISSUE TITLE
Feat: Make asynciterator asynciterable

### ISSUE THREAD

**Issue by jeswr** [RubenVerborgh/AsyncIterator#89]
In particular this logic https://github.com/LDflex/LDflex-Comunica/blob/f01ece6fa8cee720061efd5ddd23ed82921555e4/src/ComunicaEngine.ts#L158-L215 should be implemented as the `[Symbol.asyncIterator]` method of `AsyncIterator`

**Comment by jacoscaz** [comment]
This would be very convenient, although we should also carefully measure differences in performance and highlight them in `README.md` as refactoring from one approach to the other is likely a non-trivial effort.

**Comment by rubensworks** [comment]
Related to #56
